//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBoxExcelConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlightBoxExcelConverter\\src\\FlightBoxExcelConverter\\data\\ARP_LSZK_062" +
            "018.csv")]
        public string DefaultImportFileName {
            get {
                return ((string)(this["DefaultImportFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlightBoxExcelConverter\\src\\FlightBoxExcelConverter\\data\\Export.csv")]
        public string DefaultExportFileName {
            get {
                return ((string)(this["DefaultExportFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlightBoxExcelConverter\\src\\FlightBoxExcelConverter\\data\\MemberList.c" +
            "sv")]
        public string MemberListFileName {
            get {
                return ((string)(this["MemberListFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlightBoxExcelConverter\\src\\FlightBoxExcelConverter\\data\\NoLdgTaxMemb" +
            "ers.csv")]
        public string NoLdgTaxMembersFileName {
            get {
                return ((string)(this["NoLdgTaxMembersFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlightBoxExcelConverter\\src\\FlightBoxExcelConverter\\data\\NoLdgTaxType" +
            "Traffic.csv")]
        public string NoLdgTaxTypeTraffic {
            get {
                return ((string)(this["NoLdgTaxTypeTraffic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\FlightBoxExcelConverter\\src\\FlightBoxExcelConverter\\data\\MemberNumber" +
            "Remapping.csv")]
        public string MemberNumberRemappingFileName {
            get {
                return ((string)(this["MemberNumberRemappingFileName"]));
            }
        }
    }
}
